export const k2_DATA_LOADED = 'k2_DATA_LOADED';
export const k2_DATA_REQUESTED = 'k2_DATA_REQUESTED';
export const k1_DATA_LOADED = 'k1_DATA_LOADED';
export const k1_DATA_REQUESTED = 'k1_DATA_REQUESTED';
export const k1 = 'k1';
export const k2 = 'k2';
// export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA = "GET_USER_DATA"
export const USER_DATA_LOADED = "USER_DATA_LOADED"